### ISSUE TITLE
봇 상호작용 실패

### ISSUE THREAD

**Issue by FilePile2856** [Not-swasd/classcard-hack-discord#11]
<img width="318" alt="image" src="https://github.com/Not-swasd/classcard-hack-discord/assets/88542418/da2decec-19a5-4da2-9f77-c5c1de4ef56a">

**Comment by Not-swasd** [comment]
콘솔 내용도 없고 이슈 템플릿도 지키지 않았고 설명도 없는데 제가 초능력자도 아니고 어떻게 도와드리나요? 그리고 소스 상 문제는 없습니다 테스트도 해봤고요. 이슈 닫겠습니다.
