### ISSUE TITLE
config.json 및 users.json 생성안됨

### ISSUE THREAD

**Issue by lbt433** [Not-swasd/classcard-hack-discord#12]
말 그대로입니다
npm start를 실행 후 생성된 config.json 파일을 수정합니다. (디스코드 봇 토큰, 디스코드 봇 소유자 id, 서버 id)

이 부분에서 config.json 파일이 생성이 되지않습니다.

**Comment by Not-swasd** [comment]
이슈를 열 때는 노드 버전, npm 버전, 로그, 어디서 어떻게 무엇을 하였을 때 뭐가 안되는지 정도는 기본입니다. 이슈 닫겠습니다 다 첨부해서 오세요. 그렇게만 말 하면 이게 본인의 문제인지, 프로그램의 문제인지 어떻게 알아요
