### ISSUE TITLE
npm start 실행 후 config.json 및 users.json 파일이 생성되지 않습니다

### ISSUE THREAD

**Issue by math2653** [Not-swasd/classcard-hack-discord#13]
테스트 환경
Nodejs : 18.17.1
npm : 9.6.7
---------------------------------------------------------------------------------------------------------
npm start 실행 후 config.json 및 users.json 파일이 생성되지 않습니다
---------------------------------------------------------------------------------------------------------
```
$ sudo npm start

> hack@1.0.0 start
> tsc --project tsconfig.json && node index.js

index.ts:15:20 - error TS2307: Cannot find module './config.json' or its corresponding type declarations.

15 import config from "./config.json" assert { type: "json" };
                      ~~~~~~~~~~~~~~~

index.ts:16:20 - error TS2307: Cannot find module './users.json' or its corresponding type declarations.

16 import _users from "./users.json" assert { type: "json" };
                      ~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: index.ts:15
```

**Comment by Not-swasd** [comment]
해당 오류와는 관련이 없지만 현재 클래스카드 API 버전 V2가 배포됨에따라 이 프로그램은 정상 작동이 어려운 것으로 보입니다. 제가 이 프로젝트를 유지 보수할 시간이 없어서 Public Archive로 전환할 예정입니다. 이슈 닫겠습니다.
